### ISSUE TITLE
enable tcp_fastopen if available failed if kernel version >= 4.12

### ISSUE THREAD

**Issue by Willian-Zhang** [sparanoid/ansible-shadowsocks-libev#3]
### purposed change

In `tasks/main.yml`
``` yml
- name: enable tcp_fastopen if available
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: 3
    state: present
    reload: yes
  when: shadowsocks_fast_open and shadowsocks_sysctl_tweak and ansible_kernel is version_compare('3.7', '>=') and ansible_kernel is version_compare('4.12', '<=')
  tags: sysctl
```
